export const DomesticRoutes = [
{ from: 'NewYork', to: 'Houston', departCode: 'JFK', ArrivalCode: 'IAH' },
  { from: 'NewYork', to: 'Phoenix', departCode: 'JFK', ArrivalCode: 'PHX' },
  { from: 'NewYork', to: 'Philadelphia', departCode: 'JFK', ArrivalCode: 'PHL' },
  { from: 'NewYork', to: 'SanAntonio', departCode: 'JFK', ArrivalCode: 'SAT' },
  { from: 'NewYork', to: 'SanDiego', departCode: 'JFK', ArrivalCode: 'SAN' },
  { from: 'NewYork', to: 'Dallas', departCode: 'JFK', ArrivalCode: 'DFW' },
  { from: 'NewYork', to: 'SanJose', departCode: 'JFK', ArrivalCode: 'SJC' },
  { from: 'NewYork', to: 'Austin', departCode: 'JFK', ArrivalCode: 'AUS' },
  { from: 'NewYork', to: 'Jacksonville', departCode: 'JFK', ArrivalCode: 'JAX' },
  { from: 'NewYork', to: 'FortWorth', departCode: 'JFK', ArrivalCode: 'DFW' }, // Same airport as Dallas
  { from: 'NewYork', to: 'Columbus', departCode: 'JFK', ArrivalCode: 'CMH' },
  { from: 'NewYork', to: 'Charlotte', departCode: 'JFK', ArrivalCode: 'CLT' },
  { from: 'NewYork', to: 'SanFrancisco', departCode: 'JFK', ArrivalCode: 'SFO' },
  { from: 'NewYork', to: 'Indianapolis', departCode: 'JFK', ArrivalCode: 'IND' },
  { from: 'NewYork', to: 'Seattle', departCode: 'JFK', ArrivalCode: 'SEA' },
  { from: 'NewYork', to: 'Denver', departCode: 'JFK', ArrivalCode: 'DEN' },
  { from: 'NewYork', to: 'Washington', departCode: 'JFK', ArrivalCode: 'DCA' }, // Could also be IAD
  { from: 'NewYork', to: 'Boston', departCode: 'JFK', ArrivalCode: 'BOS' },
  { from: 'NewYork', to: 'ElPaso', departCode: 'JFK', ArrivalCode: 'ELP' },
  { from: 'NewYork', to: 'Nashville', departCode: 'JFK', ArrivalCode: 'BNA' },
  { from: 'NewYork', to: 'Detroit', departCode: 'JFK', ArrivalCode: 'DTW' },
  { from: 'NewYork', to: 'Oklahoma', departCode: 'JFK', ArrivalCode: 'OKC' },
  { from: 'LosAngeles', to: 'NewYork', departCode: 'LAX', ArrivalCode: 'JFK' },
  { from: 'LosAngeles', to: 'Chicago', departCode: 'LAX', ArrivalCode: 'ORD' },
  { from: 'LosAngeles', to: 'Houston', departCode: 'LAX', ArrivalCode: 'IAH' },
  { from: 'LosAngeles', to: 'Phoenix', departCode: 'LAX', ArrivalCode: 'PHX' },
  { from: 'LosAngeles', to: 'Philadelphia', departCode: 'LAX', ArrivalCode: 'PHL' },
   { from: 'LosAngeles', to: 'SanAntonio', departCode: 'LAX', ArrivalCode: 'SAT' },
  { from: 'LosAngeles', to: 'SanDiego', departCode: 'LAX', ArrivalCode: 'SAN' },
  { from: 'LosAngeles', to: 'Dallas', departCode: 'LAX', ArrivalCode: 'DFW' },
  { from: 'LosAngeles', to: 'SanJose', departCode: 'LAX', ArrivalCode: 'SJC' },
  { from: 'LosAngeles', to: 'Austin', departCode: 'LAX', ArrivalCode: 'AUS' },
  { from: 'LosAngeles', to: 'Jacksonville', departCode: 'LAX', ArrivalCode: 'JAX' },
  { from: 'LosAngeles', to: 'FortWorth', departCode: 'LAX', ArrivalCode: 'DFW' }, // Same as Dallas
  { from: 'LosAngeles', to: 'Columbus', departCode: 'LAX', ArrivalCode: 'CMH' },
  { from: 'LosAngeles', to: 'Charlotte', departCode: 'LAX', ArrivalCode: 'CLT' },
  { from: 'LosAngeles', to: 'SanFrancisco', departCode: 'LAX', ArrivalCode: 'SFO' },
  { from: 'LosAngeles', to: 'Indianapolis', departCode: 'LAX', ArrivalCode: 'IND' },
  { from: 'LosAngeles', to: 'Seattle', departCode: 'LAX', ArrivalCode: 'SEA' },
  { from: 'LosAngeles', to: 'Denver', departCode: 'LAX', ArrivalCode: 'DEN' },
  { from: 'LosAngeles', to: 'Washington', departCode: 'LAX', ArrivalCode: 'DCA' }, // or IAD
  { from: 'LosAngeles', to: 'Boston', departCode: 'LAX', ArrivalCode: 'BOS' },
  { from: 'LosAngeles', to: 'ElPaso', departCode: 'LAX', ArrivalCode: 'ELP' },
  { from: 'LosAngeles', to: 'Nashville', departCode: 'LAX', ArrivalCode: 'BNA' },
  { from: 'LosAngeles', to: 'Detroit', departCode: 'LAX', ArrivalCode: 'DTW' },
  { from: 'LosAngeles', to: 'Oklahoma', departCode: 'LAX', ArrivalCode: 'OKC' },

  // Chicago to other cities
  { from: 'Chicago', to: 'NewYork', departCode: 'ORD', ArrivalCode: 'JFK' },
  { from: 'Chicago', to: 'LosAngeles', departCode: 'ORD', ArrivalCode: 'LAX' },
  { from: 'Chicago', to: 'Houston', departCode: 'ORD', ArrivalCode: 'IAH' },
  { from: 'Chicago', to: 'Phoenix', departCode: 'ORD', ArrivalCode: 'PHX' },
  { from: 'Chicago', to: 'Philadelphia', departCode: 'ORD', ArrivalCode: 'PHL' },
  { from: 'Chicago', to: 'SanAntonio', departCode: 'ORD', ArrivalCode: 'SAT' },
  { from: 'Chicago', to: 'SanDiego', departCode: 'ORD', ArrivalCode: 'SAN' },
  { from: 'Chicago', to: 'Dallas', departCode: 'ORD', ArrivalCode: 'DFW' },
  { from: 'Chicago', to: 'SanJose', departCode: 'ORD', ArrivalCode: 'SJC' },
  { from: 'Chicago', to: 'Austin', departCode: 'ORD', ArrivalCode: 'AUS' },
  { from: 'Chicago', to: 'Jacksonville', departCode: 'ORD', ArrivalCode: 'JAX' },
   // Chicago to other cities
  { from: 'Chicago', to: 'FortWorth', departCode: 'ORD', ArrivalCode: 'DFW' },
  { from: 'Chicago', to: 'Columbus', departCode: 'ORD', ArrivalCode: 'CMH' },
  { from: 'Chicago', to: 'Charlotte', departCode: 'ORD', ArrivalCode: 'CLT' },
  { from: 'Chicago', to: 'SanFrancisco', departCode: 'ORD', ArrivalCode: 'SFO' },
  { from: 'Chicago', to: 'Indianapolis', departCode: 'ORD', ArrivalCode: 'IND' },
  { from: 'Chicago', to: 'Seattle', departCode: 'ORD', ArrivalCode: 'SEA' },
  { from: 'Chicago', to: 'Denver', departCode: 'ORD', ArrivalCode: 'DEN' },
  { from: 'Chicago', to: 'Washington', departCode: 'ORD', ArrivalCode: 'DCA' }, // or IAD
  { from: 'Chicago', to: 'Boston', departCode: 'ORD', ArrivalCode: 'BOS' },
  { from: 'Chicago', to: 'ElPaso', departCode: 'ORD', ArrivalCode: 'ELP' },
  { from: 'Chicago', to: 'Nashville', departCode: 'ORD', ArrivalCode: 'BNA' },
  { from: 'Chicago', to: 'Detroit', departCode: 'ORD', ArrivalCode: 'DTW' },
  { from: 'Chicago', to: 'Oklahoma', departCode: 'ORD', ArrivalCode: 'OKC' },

  // Houston to other cities
  { from: 'Houston', to: 'NewYork', departCode: 'IAH', ArrivalCode: 'JFK' },
  { from: 'Houston', to: 'LosAngeles', departCode: 'IAH', ArrivalCode: 'LAX' },
  { from: 'Houston', to: 'Chicago', departCode: 'IAH', ArrivalCode: 'ORD' },
  { from: 'Houston', to: 'Phoenix', departCode: 'IAH', ArrivalCode: 'PHX' },
  { from: 'Houston', to: 'Philadelphia', departCode: 'IAH', ArrivalCode: 'PHL' },
  { from: 'Houston', to: 'SanAntonio', departCode: 'IAH', ArrivalCode: 'SAT' },
  { from: 'Houston', to: 'SanDiego', departCode: 'IAH', ArrivalCode: 'SAN' },
  { from: 'Houston', to: 'Dallas', departCode: 'IAH', ArrivalCode: 'DFW' },
  { from: 'Houston', to: 'SanJose', departCode: 'IAH', ArrivalCode: 'SJC' },
  { from: 'Houston', to: 'Austin', departCode: 'IAH', ArrivalCode: 'AUS' },
  { from: 'Houston', to: 'Jacksonville', departCode: 'IAH', ArrivalCode: 'JAX' },
  { from: 'Houston', to: 'FortWorth', departCode: 'IAH', ArrivalCode: 'DFW' },
  { from: 'Houston', to: 'Columbus', departCode: 'IAH', ArrivalCode: 'CMH' },
  { from: 'Houston', to: 'Charlotte', departCode: 'IAH', ArrivalCode: 'CLT' },
  { from: 'Houston', to: 'SanFrancisco', departCode: 'IAH', ArrivalCode: 'SFO' },
  { from: 'Houston', to: 'Indianapolis', departCode: 'IAH', ArrivalCode: 'IND' },
  { from: 'Houston', to: 'Seattle', departCode: 'IAH', ArrivalCode: 'SEA' },
   // Houston to remaining cities
  { from: 'Houston', to: 'Denver', departCode: 'IAH', ArrivalCode: 'DEN' },
  { from: 'Houston', to: 'Washington', departCode: 'IAH', ArrivalCode: 'DCA' }, // or IAD
  { from: 'Houston', to: 'Boston', departCode: 'IAH', ArrivalCode: 'BOS' },
  { from: 'Houston', to: 'ElPaso', departCode: 'IAH', ArrivalCode: 'ELP' },
  { from: 'Houston', to: 'Nashville', departCode: 'IAH', ArrivalCode: 'BNA' },
  { from: 'Houston', to: 'Detroit', departCode: 'IAH', ArrivalCode: 'DTW' },
  { from: 'Houston', to: 'Oklahoma', departCode: 'IAH', ArrivalCode: 'OKC' },

  // Phoenix to other cities
  { from: 'Phoenix', to: 'NewYork', departCode: 'PHX', ArrivalCode: 'JFK' },
  { from: 'Phoenix', to: 'LosAngeles', departCode: 'PHX', ArrivalCode: 'LAX' },
  { from: 'Phoenix', to: 'Chicago', departCode: 'PHX', ArrivalCode: 'ORD' },
  { from: 'Phoenix', to: 'Houston', departCode: 'PHX', ArrivalCode: 'IAH' },
  { from: 'Phoenix', to: 'Philadelphia', departCode: 'PHX', ArrivalCode: 'PHL' },
  { from: 'Phoenix', to: 'SanAntonio', departCode: 'PHX', ArrivalCode: 'SAT' },
  { from: 'Phoenix', to: 'SanDiego', departCode: 'PHX', ArrivalCode: 'SAN' },
  { from: 'Phoenix', to: 'Dallas', departCode: 'PHX', ArrivalCode: 'DFW' },
  { from: 'Phoenix', to: 'SanJose', departCode: 'PHX', ArrivalCode: 'SJC' },
  { from: 'Phoenix', to: 'Austin', departCode: 'PHX', ArrivalCode: 'AUS' },
  { from: 'Phoenix', to: 'Jacksonville', departCode: 'PHX', ArrivalCode: 'JAX' },
  { from: 'Phoenix', to: 'FortWorth', departCode: 'PHX', ArrivalCode: 'DFW' },
  { from: 'Phoenix', to: 'Columbus', departCode: 'PHX', ArrivalCode: 'CMH' },
  { from: 'Phoenix', to: 'Charlotte', departCode: 'PHX', ArrivalCode: 'CLT' },
  { from: 'Phoenix', to: 'SanFrancisco', departCode: 'PHX', ArrivalCode: 'SFO' },
  { from: 'Phoenix', to: 'Indianapolis', departCode: 'PHX', ArrivalCode: 'IND' },
  { from: 'Phoenix', to: 'Seattle', departCode: 'PHX', ArrivalCode: 'SEA' },
  { from: 'Phoenix', to: 'Denver', departCode: 'PHX', ArrivalCode: 'DEN' },
  { from: 'Phoenix', to: 'Washington', departCode: 'PHX', ArrivalCode: 'DCA' }, // or IAD
  { from: 'Phoenix', to: 'Boston', departCode: 'PHX', ArrivalCode: 'BOS' },
  { from: 'Phoenix', to: 'ElPaso', departCode: 'PHX', ArrivalCode: 'ELP' },
  { from: 'Phoenix', to: 'Nashville', departCode: 'PHX', ArrivalCode: 'BNA' },
  { from: 'Phoenix', to: 'Detroit', departCode: 'PHX', ArrivalCode: 'DTW' },
  { from: 'Phoenix', to: 'Oklahoma', departCode: 'PHX', ArrivalCode: 'OKC' },

  // Philadelphia to other cities
  { from: 'Philadelphia', to: 'NewYork', departCode: 'PHL', ArrivalCode: 'JFK' },
  { from: 'Philadelphia', to: 'LosAngeles', departCode: 'PHL', ArrivalCode: 'LAX' },
  { from: 'Philadelphia', to: 'Chicago', departCode: 'PHL', ArrivalCode: 'ORD' },
  { from: 'Philadelphia', to: 'Houston', departCode: 'PHL', ArrivalCode: 'IAH' },
  { from: 'Philadelphia', to: 'Phoenix', departCode: 'PHL', ArrivalCode: 'PHX' },
  { from: 'Philadelphia', to: 'SanAntonio', departCode: 'PHL', ArrivalCode: 'SAT' },
  { from: 'Philadelphia', to: 'SanDiego', departCode: 'PHL', ArrivalCode: 'SAN' },
  { from: 'Philadelphia', to: 'Dallas', departCode: 'PHL', ArrivalCode: 'DFW' },
  { from: 'Philadelphia', to: 'SanJose', departCode: 'PHL', ArrivalCode: 'SJC' },
  { from: 'Philadelphia', to: 'Austin', departCode: 'PHL', ArrivalCode: 'AUS' },
  { from: 'Philadelphia', to: 'Jacksonville', departCode: 'PHL', ArrivalCode: 'JAX' },
  { from: 'Philadelphia', to: 'FortWorth', departCode: 'PHL', ArrivalCode: 'DFW' },
  { from: 'Philadelphia', to: 'Columbus', departCode: 'PHL', ArrivalCode: 'CMH' },
  { from: 'Philadelphia', to: 'Charlotte', departCode: 'PHL', ArrivalCode: 'CLT' },
  { from: 'Philadelphia', to: 'SanFrancisco', departCode: 'PHL', ArrivalCode: 'SFO' },
  { from: 'Philadelphia', to: 'Indianapolis', departCode: 'PHL', ArrivalCode: 'IND' },
  { from: 'Philadelphia', to: 'Seattle', departCode: 'PHL', ArrivalCode: 'SEA' },
  { from: 'Philadelphia', to: 'Denver', departCode: 'PHL', ArrivalCode: 'DEN' },
  { from: 'Philadelphia', to: 'Washington', departCode: 'PHL', ArrivalCode: 'DCA' }, // or IAD
  { from: 'Philadelphia', to: 'Boston', departCode: 'PHL', ArrivalCode: 'BOS' },
  { from: 'Philadelphia', to: 'ElPaso', departCode: 'PHL', ArrivalCode: 'ELP' },
  { from: 'Philadelphia', to: 'Nashville', departCode: 'PHL', ArrivalCode: 'BNA' },
  { from: 'Philadelphia', to: 'Detroit', departCode: 'PHL', ArrivalCode: 'DTW' },
  { from: 'Philadelphia', to: 'Oklahoma', departCode: 'PHL', ArrivalCode: 'OKC' },

  // SanAntonio to other cities
  { from: 'SanAntonio', to: 'NewYork', departCode: 'SAT', ArrivalCode: 'JFK' },
  { from: 'SanAntonio', to: 'LosAngeles', departCode: 'SAT', ArrivalCode: 'LAX' },
  { from: 'SanAntonio', to: 'Chicago', departCode: 'SAT', ArrivalCode: 'ORD' },
  { from: 'SanAntonio', to: 'Houston', departCode: 'SAT', ArrivalCode: 'IAH' },
  { from: 'SanAntonio', to: 'Phoenix', departCode: 'SAT', ArrivalCode: 'PHX' },
  { from: 'SanAntonio', to: 'Philadelphia', departCode: 'SAT', ArrivalCode: 'PHL' },
  { from: 'SanAntonio', to: 'SanDiego', departCode: 'SAT', ArrivalCode: 'SAN' },
  { from: 'SanAntonio', to: 'Dallas', departCode: 'SAT', ArrivalCode: 'DFW' },
  { from: 'SanAntonio', to: 'SanJose', departCode: 'SAT', ArrivalCode: 'SJC' },
  { from: 'SanAntonio', to: 'Austin', departCode: 'SAT', ArrivalCode: 'AUS' },
  { from: 'SanAntonio', to: 'Jacksonville', departCode: 'SAT', ArrivalCode: 'JAX' },
  { from: 'SanAntonio', to: 'FortWorth', departCode: 'SAT', ArrivalCode: 'DFW' },
  { from: 'SanAntonio', to: 'Columbus', departCode: 'SAT', ArrivalCode: 'CMH' },
  { from: 'SanAntonio', to: 'Charlotte', departCode: 'SAT', ArrivalCode: 'CLT' },
  { from: 'SanAntonio', to: 'SanFrancisco', departCode: 'SAT', ArrivalCode: 'SFO' },
    // SanAntonio to remaining destinations
  { from: 'SanAntonio', to: 'Indianapolis', departCode: 'SAT', ArrivalCode: 'IND' },
  { from: 'SanAntonio', to: 'Seattle', departCode: 'SAT', ArrivalCode: 'SEA' },
  { from: 'SanAntonio', to: 'Denver', departCode: 'SAT', ArrivalCode: 'DEN' },
  { from: 'SanAntonio', to: 'Washington', departCode: 'SAT', ArrivalCode: 'DCA' }, // or IAD
  { from: 'SanAntonio', to: 'Boston', departCode: 'SAT', ArrivalCode: 'BOS' },
  { from: 'SanAntonio', to: 'ElPaso', departCode: 'SAT', ArrivalCode: 'ELP' },
  { from: 'SanAntonio', to: 'Nashville', departCode: 'SAT', ArrivalCode: 'BNA' },
  { from: 'SanAntonio', to: 'Detroit', departCode: 'SAT', ArrivalCode: 'DTW' },
  { from: 'SanAntonio', to: 'Oklahoma', departCode: 'SAT', ArrivalCode: 'OKC' },

  // SanDiego to other cities
  { from: 'SanDiego', to: 'NewYork', departCode: 'SAN', ArrivalCode: 'JFK' },
  { from: 'SanDiego', to: 'LosAngeles', departCode: 'SAN', ArrivalCode: 'LAX' },
  { from: 'SanDiego', to: 'Chicago', departCode: 'SAN', ArrivalCode: 'ORD' },
  { from: 'SanDiego', to: 'Houston', departCode: 'SAN', ArrivalCode: 'IAH' },
  { from: 'SanDiego', to: 'Phoenix', departCode: 'SAN', ArrivalCode: 'PHX' },
  { from: 'SanDiego', to: 'Philadelphia', departCode: 'SAN', ArrivalCode: 'PHL' },
  { from: 'SanDiego', to: 'SanAntonio', departCode: 'SAN', ArrivalCode: 'SAT' },
  { from: 'SanDiego', to: 'Dallas', departCode: 'SAN', ArrivalCode: 'DFW' },
  { from: 'SanDiego', to: 'SanJose', departCode: 'SAN', ArrivalCode: 'SJC' },
  { from: 'SanDiego', to: 'Austin', departCode: 'SAN', ArrivalCode: 'AUS' },
  { from: 'SanDiego', to: 'Jacksonville', departCode: 'SAN', ArrivalCode: 'JAX' },
  { from: 'SanDiego', to: 'FortWorth', departCode: 'SAN', ArrivalCode: 'DFW' },
  { from: 'SanDiego', to: 'Columbus', departCode: 'SAN', ArrivalCode: 'CMH' },
  { from: 'SanDiego', to: 'Charlotte', departCode: 'SAN', ArrivalCode: 'CLT' },
  { from: 'SanDiego', to: 'SanFrancisco', departCode: 'SAN', ArrivalCode: 'SFO' },
  { from: 'SanDiego', to: 'Indianapolis', departCode: 'SAN', ArrivalCode: 'IND' },
  { from: 'SanDiego', to: 'Seattle', departCode: 'SAN', ArrivalCode: 'SEA' },
  { from: 'SanDiego', to: 'Denver', departCode: 'SAN', ArrivalCode: 'DEN' },
  { from: 'SanDiego', to: 'Washington', departCode: 'SAN', ArrivalCode: 'DCA' },
  { from: 'SanDiego', to: 'Boston', departCode: 'SAN', ArrivalCode: 'BOS' },
  { from: 'SanDiego', to: 'ElPaso', departCode: 'SAN', ArrivalCode: 'ELP' },
  { from: 'SanDiego', to: 'Nashville', departCode: 'SAN', ArrivalCode: 'BNA' },
  { from: 'SanDiego', to: 'Detroit', departCode: 'SAN', ArrivalCode: 'DTW' },
  { from: 'SanDiego', to: 'Oklahoma', departCode: 'SAN', ArrivalCode: 'OKC' },

  // Dallas to other cities
  { from: 'Dallas', to: 'NewYork', departCode: 'DFW', ArrivalCode: 'JFK' },
  { from: 'Dallas', to: 'LosAngeles', departCode: 'DFW', ArrivalCode: 'LAX' },
  { from: 'Dallas', to: 'Chicago', departCode: 'DFW', ArrivalCode: 'ORD' },
  { from: 'Dallas', to: 'Houston', departCode: 'DFW', ArrivalCode: 'IAH' },
  { from: 'Dallas', to: 'Phoenix', departCode: 'DFW', ArrivalCode: 'PHX' },
  { from: 'Dallas', to: 'Philadelphia', departCode: 'DFW', ArrivalCode: 'PHL' },
  { from: 'Dallas', to: 'SanAntonio', departCode: 'DFW', ArrivalCode: 'SAT' },
  { from: 'Dallas', to: 'SanDiego', departCode: 'DFW', ArrivalCode: 'SAN' }
  ];
  